### ISSUE TITLE
The text starts from the middle when a TextView has an initial height

### ISSUE THREAD

**Issue by minimaluminium** [SwiftUI-Plus/TextView#10]
## General Information

 - Project version: 1.1.0
 
 
 - Platform/OS version: iOS >= 14
 
 
 - IDE version: Xcode 13.4.1
 
 
 - Devices: iPhone 13 mini
 

## Describe the bug
The text starts from the middle when a TextView has an initial height.

## Steps to reproduce
1. Add a TextView
2. Add a `frame` modifier to set the minimum height

```swift
TextView($text)
    .placeholder("Description")
    .frame(minHeight: 80, maxHeight: .infinity)
```

## Expected behavior
I'm trying to replicate the new reminder form ("Notes" field) of the default Reminder app which has a minimum height to start with and grows with the content. This library handles it like a pro except one tiny issue that the text alignment is in the middle instead of top.

<img src="https://user-images.githubusercontent.com/1418797/172992814-c22769dc-832d-4dd1-b6db-ca05fdbb28b9.jpeg" width="400">

## Screenshots

<img width="357" alt="CleanShot 2022-06-10 at 12 43 52@2x" src="https://user-images.githubusercontent.com/1418797/172993525-2f6a4c90-3192-4c51-9038-3e5f8e124eaf.png">

**Comment by shaps80** [comment]
To be honest right now I'm actually rewriting a lot of the internals for this view, bare with me but I'm fairly certain the new code resolves this concern as well as a few others.
