### ISSUE TITLE
TextView Doesn't respect "frame" height when set

### ISSUE THREAD

**Issue by kuvermaexpedia** [SwiftUI-Plus/TextView#13]
If the TextView's height is set like .frame(height: 100) the text still goes out of bounds and it also starts in the middle by default.
In the cases where height of the view or parent is fixed the text should become scrollable.

**Comment by shaps80** [comment]
@kuvermaexpedia have you set the modifier `enableScrolling(false)` on the TextView?

Basically that also disables auto-sizing, allowing you to use a fixed frame.

**Comment by shaps80** [comment]
Closing since this isn’t a problem I can solve and its slightly by-design. Perhaps feels unexpected in this specific scenario but I prefer the use of the API to add `.clipped()` rather than I assume it, and then you can’t undo it.
