### ISSUE TITLE
Cursor always jumps to the end when editing text

### ISSUE THREAD

**Issue by teffi** [SwiftUI-Plus/TextView#5]
## General Information

 - Project version:
1.1.0
 
 - Platform/OS version: 
iOS 14 and 15
 
 - IDE version:
Xcode 13
 
 - Devices: 
iPhone 12, iPhone X

## Describe the bug
Cursor always jumps to the end when editing text

## Steps to reproduce
* Type "Hello World"
* Move cursor to the beginning
* Type "A"

## Expected behavior
Cursor should be after "A"

## Actual behavior
Cursor automatically moves to the end of the text.

## Video

https://user-images.githubusercontent.com/3197049/157152747-5c38b183-233c-4a24-8b9f-0d03d98d5554.mov

## Additional context
Since you set the text on update ui, the cursor naturally moves to the end. I have a forked version with a [fix](https://github.com/teffi/TextView/commit/18472f822f7e9eb9e22d0609b2700f6a6012422f). It's something I quickly put together so I'm not entirely confident if its clean enough for a PR request _(I'm also particularly new to SwiftUI)_ . I can send a PR if you're fine with it but if not I hope you could roll out a minor fix. 

Hope this helps. And thanks for putting this package together.

EDIT:
Replace Imgur video link with embedded video.

**Comment by shaps80** [comment]
Are you able to include a Demo app at all? @teffi I'm unable to reproduce sorry ¯\_(ツ)_/¯ 

EDIT:

Just saw your PR. I think it makes sense, make a PR and I'll test and review 👍

**Comment by teffi** [comment]
@shaps80 Updated description with demo video :)

**Comment by joemichels** [comment]
Hi,

To confirm the bug, I'm seeing it as well and it seems teffi's fix works.

**Comment by shaps80** [comment]
@joemichels / @teffi yep I can confirm as well. However the suggested implementation isn't a great fit for SwiftUI and/or as a reusable framework. I'm on holiday atm, but when I'm back next week I'll review properly and consider an alternative. Thanks!

**Comment by joemichels** [comment]
@shaps80 Has this fix been integrated into main?

**Comment by shaps80** [comment]
I thought so, was a few months back so I admit my memory is fuzzy. I'll look into this tomorrow (out atm) and get back to you. Or get it done, either way.

**Comment by TToldi** [comment]
@shaps80 Great TextView for SwiftUI! Just wondering if you have had a chance to fix the issue about the cursor?

**Comment by Matt54** [comment]
As far as I can tell, this is caused do to textView.attributedText being set in the coordinator's update method (called from updateUIView). If you instead set this in makeUIView, then the issue goes away.

**Comment by shaps80** [comment]
@Matt54 / @TToldi – so actually I have a complete re-write in-progress for this. Solves the above issue but also enables a far more SwiftUI approach. Will let you know once its ready 👍🏻
