### ISSUE TITLE
Centering via MultilineTextAlignment modifier doesn't work

### ISSUE THREAD

**Issue by thipokch** [SwiftUI-Plus/TextView#9]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

## General Information

 - Project version: 
1.1.0
 
 
 - Platform/OS version:  
iOS 14 and 15
 
 
 - IDE version:
Xcode 13
 
 
 - Devices: 
iPhone 13
 
 
 - Any related GitHub issues:
Nope

## Describe the bug
.multilineTextAlignment(.center) doesn't center align the text

## Steps to reproduce
*Provide numbered steps to follow that reproduce the bug.*
- Create a TextView()
- Add .multilineTextAlignment(.center) modifier
- Preview it

## Expected behavior
*Clearly and concisely describe what you expected to happen.*
- .multilineTextAlignment(.center) should center align the text
## Screenshots
*If applicable, add screenshots, gifs, or videos to help explain your problem.*

<img width="373" alt="Screen Shot 2022-06-08 at 10 03 26 AM" src="https://user-images.githubusercontent.com/20105675/172522664-871ec81f-92b2-4102-8553-cae925578a68.png">

**Comment by thipokch** [comment]
My bad... the border modifier return View instead of TextView

**Comment by shaps80** [comment]
Haha I was gonna say, this was working 😂 Thanks for the clarifying!
